<?php
include_once('templates/code_for_templates/redirect_if_not_login.php');
include_once('templates/elements/headher.phtml');
include_once('templates/elements/topnav.phtml');
include_once('templates/elements/menu.phtml');
?>
<div class="bg-light">
    <div class="container-fluid">
        <div class="row content">
            <div class="col-sm-12">
                <h1>WITAJ W CMS FIRMY CIRRUS</h1>
            </div>
        </div>
    </div>
</div>
<?php include_once('templates/elements/footer.phtml');?>