<?php include_once('templates/elements/headher.phtml');?>
<div class="container-fluid">
    <div class="row content">
        <div class="col-sm-3 login">
            <form action="?action=login" method="post">
                <div class="form-group">
                    <label for="login">Podaj Login</label>
                    <input class="form-control" type="text" name="login" placeholder="Login...">
                </div>
                <div class="form-group">
                    <label for="password">Podaj Hasło</label>
                    <input class="form-control" type="password" name="password" placeholder="Hasło...">
                </div>
                <div class="form-group">
                    <button class="btn btn-primary" type="submit">Zaloguj</button>
                </div>
            </form>
        </div>
    </div>
</div>
<?php include_once('templates/elements/footer.phtml');?>