<script>
    search_router_app = angular.module("searchRouterApp", []);
    search_router_app.controller("searchRouterController", function($scope){
        $scope.columns = <?php echo json_encode($columns);?>;
        $scope.columns_to_show = <?php echo json_encode($columns_to_show);?>;
        $scope.inputs = [{"choosen_column":$scope.columns[0],"fit":"Pasuje","value_for_column":"","connector":"OR"}];
        $scope.choosen_column = $scope.columns[0];
        $scope.fit = 'Pasuje';
        $scope.value_for_column = '';
        $scope.connector = 'OR';
        $scope.toSend = '';
        $scope.addInput = function(){
            $scope.inputs.push({"choosen_column":$scope.columns[0],"fit":"Pasuje","value_for_column":"","connector":"OR"});
        }
        $scope.deleteInput = function(index){
            $scope.inputs.splice(index, 1);
        }
        function compare(a, b){
            choosen_columnA = a.choosen_column;
            choosen_columnB = b.choosen_column;
            let comparison = 0;
            if(choosen_columnA > choosen_columnB){
                comparison = 1;
            }else if(choosen_columnA < choosen_columnB){
                comparison = -1;
            }
            return comparison;
        }
        $scope.setChoosenColumn = function(index, choosen_column){
            $scope.inputs[index]['choosen_column'] = choosen_column;
            $scope.inputs.sort(compare);
            $scope.toSend = JSON.stringify($scope.inputs);
        }
        $scope.setFit = function(index, fit){
            $scope.inputs[index]['fit'] = fit;
            $scope.inputs.sort(compare);
            $scope.toSend = JSON.stringify($scope.inputs);
        }
        $scope.setValueForColumn = function(index, value_for_column){
            $scope.inputs[index]['value_for_column'] = value_for_column;
            $scope.inputs.sort(compare);
            $scope.toSend = JSON.stringify($scope.inputs);
        }
        $scope.setConnector = function(index, connector){
            $scope.inputs[index]['connector'] = connector;
            $scope.inputs.sort(compare);
            $scope.toSend = JSON.stringify($scope.inputs);
        }
    });
</script>