<?php
include_once('templates/code_for_templates/redirect_if_not_login.php');
include_once('templates/lists/code_for_lists_templates/main_object_model.php');
include_once('templates/lists/code_for_lists_templates/comment_model.php');
include_once('templates/code_for_templates/client_model.php');
include_once('templates/elements/headher.phtml');
include_once('templates/elements/topnav.phtml');
include_once('templates/elements/menu.phtml');
?>
<div class="bg-light">
    <div class="container-fluid">
        <div ng-app="listObjectApp" ng-controller="listObjectControler" class="row content">  
            <div class="col-sm-12">
                <h1>
                <small>Dane Kontaktowe - wszystkie (<text ng-bind="objects.length"></text>)</small>
                    <hr>
                </h1>
                <?php include_once('templates/lists/elements/search_by_client.phtml');?>
                <?php include_once('templates/lists/elements/advanced_search.phtml');?>
                <?php if(isset($_GET['client']) && !empty($_GET['client'])):?>
                <div class="col-sm-2">
                    <a href="?action=routers&client=<?php echo $_GET['client'];?>">
                        <button class="btn btn-primary button-max-space" title="Przejź do Routerów Klienta">Routery</button>
                    </a>
                </div>
                <div class="col-sm-2">
                    <a href="?action=servers&client=<?php echo $_GET['client'];?>">
                        <button class="btn btn-primary button-max-space" title="Przejź do Serwerów Klienta">Serwery</button>
                    </a>
                </div>
                <?php endif;?>
            </div>
            <div class="col-sm-12 margin-top">
                <div class="col-sm-2">
                    <a href="?action=add_contact_details">
                        <button class="btn btn-success" title="Dodaj Dane Kontaktowe">
                            <span class="glyphicon glyphicon-plus"></span>
                        </button>
                    </a>
                </div>
                <div class="col-sm-2"></div>
                <div class="col-sm-2"></div>
                <div class="col-sm-2"></div>
                <div class="col-sm-2">
                    <select class="form-control choose-table-content" ng-model="comment_table_content" ng-change="changeCommentTableContent(comment_table_content)">
                        <option value="allComments">Wszystkie Komentarze</option>
                        <option value="archComments">Archiwalne Komentarze</option>
                        <option value="inUseComments">Używane Komentarze</option>
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control choose-table-content" ng-model="object_table_content" ng-change="changeObjectTableContent(object_table_content)">
                        <option value="allObjects">Wszystkie Dane Kontaktowe</option>
                        <option value="archObjects">Archiwalne Dane Kontaktowe</option>
                        <option value="inUseObjects">Używane Dane Kontaktowe</option>
                    </select>
                </div>
                <div class="search-padding">
                </div>
            </div>
            <div class="col-sm-12">
                <div class="form-group">
                    <div class="col-sm-2">
                        <input ng-model="searchClient" class="form-control" type="text" placeholder="Szukaj Klienta..." title="Szukaj Klienta...">
                    </div>
                    <div class="col-sm-2">
                        <input ng-model="searchFirstname" class="form-control" type="text" placeholder="Szukaj Imienia..." title="Szukaj Imienia...">
                    </div>
                    <div class="col-sm-2">
                        <input ng-model="searchLastname" class="form-control" type="text" placeholder="Szukaj Nazwiska..." title="Szukaj Nazwiska...">
                    </div>
                    <div class="col-sm-2">
                        <input ng-model="searchPhone" class="form-control" type="text" placeholder="Szukaj Numeru Telefonu..." title="Szukaj Numeru Telefonu...">
                    </div>
                    <div class="col-sm-2">
                        <input ng-model="searchMobilePhone" class="form-control" type="text" placeholder="Szukaj Numeru Komórkowego..." title="Szukaj Numeru Komórkowego...">
                    </div>
                    <div class="col-sm-2">
                        <input ng-model="searchEmail" class="form-control" type="text" placeholder="Szukaj Email..." title="Szukaj Email...">
                    </div>
                </div>
                <div class="search-padding">
                </div>
                <table class="table table-hover table-bordered table-cells text-center-and-middle">       
                    <thead>    
                    </thead>
                    <tbody ng-repeat="object in objects | filter: {client: searchClient, firstname: searchFirstname, lastname: searchLastname, phone: searchPhone, mobile_phone: searchMobilePhone, email: searchEmail} | orderBy: 'client' | orderBy: objectOrderBy">
                        <tr class="th-main">
                            <th class="take-content-size-of-cell">ID</th>
                            <th ng-click="orderByMe('client')" title="Sortuj według klientów">Klient</th>
                            <th ng-click="orderByMe('firstname')" title="Sortuj według lokalizacji">Imię</th>
                            <th ng-click="orderByMe('lastname')" title="Sortuj według typu">Nazwisko</th>
                            <th ng-click="orderByMe('phone')" title="Sortuj według systemu operacyjnego">Telefony</th>
                            <th ng-click="orderByMe('mobile_phone')">Komórka</th>
                            <th ng-click="orderByMe('email')">Email</th>
                            <th colspan="2" class="take-content-size-of-cell">Akcje</th>
                        </tr>
                        <tr>
                            <th scope="row" rowspan="4" ng-bind="$index+1"></th>
                            <td ng-bind="object.client"></td>
                            <td ng-bind="object.firstname"></td>
                            <td ng-bind="object.lastname"></td>
                            <td class="no-cell-hover no-padding">
                                <table class="table table-hover no-margin-bottom table-bordered-in-table">
                                    <tbody ng-repeat="phone in object.phone track by $index">
                                        <tr>
                                            <td ng-bind="phone"></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </td>
                            <td class="no-cell-hover no-padding">
                                <table class="table table-hover no-margin-bottom table-bordered-in-table">
                                    <tbody ng-repeat="mobile_phone in object.mobile_phone track by $index">
                                        <tr>
                                            <td ng-bind="mobile_phone"></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </td>
                            <td class="no-cell-hover no-padding">
                                <table class="table table-hover no-margin-bottom table-bordered-in-table">
                                    <tbody ng-repeat="email in object.email track by $index">
                                        <tr>
                                            <td ng-bind="email"></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </td>
                            <td rowspan="4" class="take-content-size-of-cell ">
                                <a ng-if="object.arch == 1" href="?action=restore_contact_details&id={{object.id}}">
                                    <button ng-if="object.arch == 1" type="button" class="btn btn-info" title="Przywróć">
                                        <span ng-if="object.arch == 1" class="glyphicon glyphicon-share-alt"></span>
                                    </button>
                                </a>
                                <a ng-if="object.arch == 0" href="?action=edit_contact_details&id={{object.id}}">
                                    <button ng-if="object.arch == 0" type="button" class="btn btn-info" title="Edytuj">
                                        <span ng-if="object.arch == 0" class="glyphicon glyphicon-pencil"></span>
                                    </button>
                                </a>
                            </td>
                            <td rowspan="4" class="take-content-size-of-cell ">
                                <button ng-if="object.arch == 0" ng-click="archObjectAlert(object.id)" type="button" class="btn btn-danger" title="Archiwizuj">
                                    <span ng-if="object.arch == 0" class="glyphicon glyphicon-share-alt"></span>
                                </button>
                                <button ng-if="object.arch == 1" ng-click="deleteObjectAlert(object.id)" type="button" class="btn btn-danger" title="Usuń">
                                    <span ng-if="object.arch == 1" class="glyphicon glyphicon-trash"></span>
                                </button>
                            </td>
                        </tr>
                        <?php include_once('templates/lists/elements/comments.phtml');?>
                    </tbody>
                </table>
            </div>
            <?php include_once('templates/lists/angular_script_selector/list_object_app.phtml');?>
        </div>
    </div>
</div>
<?php include_once('templates/elements/footer.phtml');?>