<?php
include_once('templates/code_for_templates/redirect_if_not_login.php');
include_once('templates/add_edit/code_for_add_edit_templates/main_object_model.php');
include_once('templates/code_for_templates/client_model.php');
include_once('templates/code_for_templates/tag_model.php');
include_once('templates/elements/headher.phtml');
include_once('templates/elements/topnav.phtml');
include_once('templates/elements/menu.phtml');
?>
<div class="bg-light">
    <div class="container-fluid">
        <div ng-app="objectAddEditApp" ng-controller="objectAddEditController" class="row content">
            <div class="col-sm-12">
                <h1>
                    <?php if($this->getElementId() !== null && !empty($this->getElementId())):?>
                        <small>Edytuj Dane Kontaktowe - id: <?php echo $this->getElementId();?></small>   
                    <?php else:?>
                        <small>Dodaj Dane Kontaktowe</small>
                    <?php endif;?>
                    <hr>
                </h1>
                <form action="?action=<?php echo substr($this->getAction(), strpos($this->getAction(), '_') + 1, strlen($this->getAction()));?>" method="post">
                    <input type="hidden" name="table" value="<?php echo substr($this->getAction(), strpos($this->getAction(), '_') + 1, strlen($this->getAction()));?>">
                    <input type="hidden" name="arch" value="0">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <?php if($this->getElementId() !== null && !empty($this->getElementId())):?>
                            <input type="hidden" name="id" value="<?php echo $this->getElementId();?>">
                            <?php endif;?>
                            <label for="client">Klient</label>
                            <input list="client-list" class="form-control" type="text" name="client" ng-model="client" ng-change="checkIfItIsNewClient()" placeholder="Podaj klienta..." autocomplete="off" required>
                            <datalist id="client-list">
                                <option ng-repeat="client in clients" value="{{client.client}}">
                            </datalist>
                        </div>
                        <div class="form-group">
                            <label for="firstname">Imię</label>
                            <input class="form-control" type="text" name="firstname" ng-model="firstname" placeholder="Podaj Imię..." required>
                        </div>
                        <div class="form-group">
                            <label for="lastname">Nazwisko</label>
                            <input class="form-control" type="text" name="lastname" ng-model="lastname" placeholder="Podaj Nazwisko..." required> 
                        </div>
                        <div class="block-add-edit-poli">
                            <div class="col-sm-12">
                            <label class="take-max-width" for="ip">Numery Telefonu</label>
                            <button class="btn btn-success" type="button" ng-click="addPhone()"><span class="glyphicon glyphicon-plus"></span></button>
                            <hr class="min-hr">
                                <div ng-repeat="input_phone in input_phones track by $index" class="form-group input-group">
                                    <button ng-if="input_phones.length != 1" class="btn btn-danger input-group-button add-edit-delete-input-group-button" type="button" ng-click="deletePhone($index)"><span class="glyphicon glyphicon-minus"></span></button>
                                    <input class="form-control input-group-input add-edit-only-one-input-group-input" type="text" ng-value="input_phones[$index]" ng-model="phone" ng-change="addPhoneNumber(phone, $index)" ng-model-options="{allowInvalid: true }" placeholder="Podaj Numer Telefonu..." pattern="[0-9]{9}" required>
                                </div>
                                <input type="hidden" name="phone" ng-value="phones">
                            </div>
                        </div>
                        <div class="block-add-edit-poli">
                            <div class="col-sm-12">
                            <label class="take-max-width" for="ip">Numery Komórkowe</label>
                            <button class="btn btn-success" type="button" ng-click="addMobilePhone()"><span class="glyphicon glyphicon-plus"></span></button>
                            <hr class="min-hr">
                                <div ng-repeat="input_mobile_phone in input_mobile_phones track by $index" class="form-group input-group">
                                    <button ng-if="input_mobile_phones.length != 1" class="btn btn-danger input-group-button add-edit-delete-input-group-button" type="button" ng-click="deleteMobilePhone($index)"><span class="glyphicon glyphicon-minus"></span></button>
                                    <input class="form-control input-group-input add-edit-only-one-input-group-input" type="text" ng-value="input_mobile_phones[$index]" ng-model="mobile_phone" ng-change="addMobilePhoneNumber(mobile_phone, $index)" ng-model-options="{allowInvalid: true }" placeholder="Podaj Numer Telefonu Komórkowego..." pattern="[0-9]{9}" required>
                                </div>
                                <input type="hidden" name="mobile_phone" ng-value="mobile_phones">
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <button class="btn btn-success take-max-width" type="submit"><?php echo ($this->getElementId() !== null && !empty($this->getElementId())) ? "Edytuj Dane Kontaktowe" : "Dodaj Dane Kontaktowe";?></button>
                                    <input type="hidden" name="new_client" ng-value="new_client">
                                    <input type="hidden" name="new_tags" ng-value="all_new_tags">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="block-add-edit-poli">
                            <div class="col-sm-12">
                            <label class="take-max-width" for="ip">Emaile</label>
                            <button class="btn btn-success" type="button" ng-click="addEmail()"><span class="glyphicon glyphicon-plus"></span></button>
                            <hr class="min-hr">
                                <div ng-repeat="input_email in input_emails track by $index" class="form-group input-group">
                                    <button ng-if="input_emails.length != 1" class="btn btn-danger input-group-button add-edit-delete-input-group-button" type="button" ng-click="deleteEmail($index)"><span class="glyphicon glyphicon-minus"></span></button>
                                    <input class="form-control input-group-input add-edit-only-one-input-group-input" type="email" ng-value="input_emails[$index]" ng-model="email" ng-change="addEmailName(email, $index)" ng-model-options="{allowInvalid: true }" placeholder="Podaj Email..." required>
                                </div>
                                <input type="hidden" name="email" ng-value="emails">
                            </div>
                        </div>
                        <div class="block-add-edit-mono">
                            <label class="take-max-width" for="tag">Tagi</label>
                            <button class="btn btn-success" type="button" ng-click="addInputTag()"><span class="glyphicon glyphicon-plus"></span></button>
                            <hr class="min-hr">
                            <div ng-repeat="input_tag in input_tags track by $index" class="form-group input-group">
                                <button ng-if="input_tags.length != 1" class="btn btn-danger input-group-button add-edit-delete-input-group-button" type="button" ng-click="deleteTag($index)"><span class="glyphicon glyphicon-minus"></span></button>
                                <input list="tag-list" class="form-control input-group-input add-edit-only-one-input-group-input" type="text" ng-value="input_tags[$index]" ng-model="tag" ng-change="addTag(tag, $index)"  placeholder="Podaj tag..." autocomplete="off" required>
                                <datalist id="tag-list">
                                    <option ng-repeat="tag in tags" value="{{tag.tag}}">
                                </datalist>
                            </div>
                            <br>
                            <input type="hidden" name="tag" ng-value="all_tags">
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <?php include_once('templates/add_edit/angular_script_selector/add_edit_object_app.phtml');?>
    </div>
</div>
<?php include_once('templates/elements/footer.phtml');?>