<div class="col-sm-2">
    <a href="?action=<?php echo $this->getAction();?>">
        <button class="btn btn-primary button-max-space btn-font-properties" title="Wyczyść Wyszukiwanie">Wyczyść Wyszukiwanie</button>
    </a>
</div>
<div class="col-sm-2">
    <a href="?action=search&search_item=<?php echo $this->getAction();?>">
        <button class="btn btn-primary button-max-space btn-font-properties" title="Wyszukiwanie Zaawansowane">Wyszukiwanie Zaawansowane</button>
    </a>
</div>